USE [master]
GO

/****** Object:  Database [PetCareServices]    Script Date: 1/30/2020 9:56:15 AM ******/
CREATE DATABASE [PetCareServices]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PetCareServices', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PetCareServices.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PetCareServices_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PetCareServices_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PetCareServices].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PetCareServices] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PetCareServices] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PetCareServices] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PetCareServices] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PetCareServices] SET ARITHABORT OFF 
GO

ALTER DATABASE [PetCareServices] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PetCareServices] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PetCareServices] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PetCareServices] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PetCareServices] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PetCareServices] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PetCareServices] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PetCareServices] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PetCareServices] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PetCareServices] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PetCareServices] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PetCareServices] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PetCareServices] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PetCareServices] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PetCareServices] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PetCareServices] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PetCareServices] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PetCareServices] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PetCareServices] SET  MULTI_USER 
GO

ALTER DATABASE [PetCareServices] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PetCareServices] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PetCareServices] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PetCareServices] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PetCareServices] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PetCareServices] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PetCareServices] SET  READ_WRITE 
GO


